//First Names
//Modified list from : https://github.com/fnichol/names/blob/master/data/adjectives.txt
//List of first names was found on: https://www.ssa.gov/oact/babynames/decades/century.html
pub const LIST: &'static [&'static str] = &[
    "Jacob",
    "Emily",
    "Michael",
    "Madison",
    "Joshua",
    "Emma",
    "Matthew",
    "Olivia",
    "Daniel",
    "Hannah",
    "Chris",
    "Abby",
    "Andrew",
    "Isabella",
    "Ethan",
    "Samantha",
    "Joe",
    "Lizzie",
    "Will",
    "Ashley",
    "James",
    "Mary",
    "John",
    "Patty",
    "Robert",
    "Jen",
    "Michael",
    "Linda",
    "Will",
    "Barb",
    "David",
    "Sue",
    "Richard",
    "Jessica",
    "Chuck",
    "Karen",
    "Dan",
    "Margaret",
    "Matt",
    "Sandra",
    "Ben",
    "Sharon"
];
